/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "vxi11core.h"
#include <math.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <stdint.h>
#include <string.h>
#include <strings.h>
#include <signal.h>
#include <time.h>

#ifdef VXI11_USE_DUKTAPE
#include "duktape.h"
#endif

enum {
	LOG_ERROR = 0,
	LOG_WARN = 1,
	LOG_INFO = 2,
	LOG_DEBUG = 3,
	LOG_TRACE = 4
};

static pthread_mutex_t g_state_lock = PTHREAD_MUTEX_INITIALIZER;
static char g_last_command[1024];
static char g_response[262144];
static size_t g_response_len = 0;
static size_t g_response_offset = 0;
static const Device_Link kLinkId = 1;

static const int kTraceMaxPoints = 10001;
static double g_trace[10001];
static int g_trace_points = 1001;
static double g_center_hz = 1.0e9;
static double g_span_hz = 10.0e6;
static double g_ref_level_dbm = 0.0;
static double g_rbw_hz = 1.0e3;
static double g_vbw_hz = 3.0e3;
static double g_sweep_time_s = 0.05;
static int g_continuous = 1;
static double g_tone_freq_hz = 98.5e6;
static double g_tone_base_hz = 98.5e6;
static double g_tone_level_dbm = -30.0;
static int g_tone_enabled = 1;
static double g_tone_drift_span_hz = 50.0e3;
static double g_tone_drift_step_hz = 5.0e3;
static double g_noise_floor_dbm = -90.0;
static double g_noise_variation_db = 3.0;
static uint64_t g_noise_state = 0;
static uint64_t g_noise_counter = 0;
static pthread_mutex_t g_log_lock = PTHREAD_MUTEX_INITIALIZER;
static int g_log_init = 0;
static int g_log_level = LOG_WARN;
static FILE *g_log_file = NULL;
static int g_marker_index = -1;
static double g_marker_freq_hz = 0.0;
static double g_marker_level_dbm = 0.0;
static int g_marker_track_max = 0;
static char g_error_msg[128];

#ifdef VXI11_USE_DUKTAPE
static duk_context *g_duk_ctx = NULL;
static int g_script_init = 0;
static int g_script_enabled = 0;
static char g_script_path[512];
#endif

static void reset_state_locked(void) {
	g_center_hz = 98.5e6;
	g_span_hz = 20.0e6;
	g_ref_level_dbm = 0.0;
	g_rbw_hz = 1.0e3;
	g_vbw_hz = 3.0e3;
	g_sweep_time_s = 0.05;
	g_trace_points = 1001;
	g_continuous = 1;
	g_tone_base_hz = 98.5e6;
	g_tone_freq_hz = g_tone_base_hz;
	g_tone_level_dbm = -30.0;
	g_tone_enabled = 1;
	g_tone_drift_span_hz = 50.0e3;
	g_tone_drift_step_hz = 5.0e3;
	g_noise_floor_dbm = -90.0;
	g_noise_variation_db = 3.0;
	g_noise_state = 0;
	g_noise_counter = 0;
	g_marker_index = -1;
	g_marker_freq_hz = 0.0;
	g_marker_level_dbm = 0.0;
	g_marker_track_max = 0;
	g_error_msg[0] = '\0';
}

static const char *log_level_name(int level) {
	switch (level) {
	case LOG_ERROR:
		return "ERROR";
	case LOG_WARN:
		return "WARN ";
	case LOG_INFO:
		return "INFO ";
	case LOG_DEBUG:
		return "DEBUG";
	case LOG_TRACE:
		return "TRACE";
	default:
		return "INFO ";
	}
}

static int parse_log_level(const char *value) {
	if (!value || !*value) {
		return LOG_INFO;
	}
	if (value[0] >= '0' && value[0] <= '9') {
		int level = atoi(value);
		if (level < LOG_ERROR) {
			level = LOG_ERROR;
		} else if (level > LOG_TRACE) {
			level = LOG_TRACE;
		}
		return level;
	}
	if (strcasecmp(value, "error") == 0) {
		return LOG_ERROR;
	}
	if (strcasecmp(value, "warn") == 0 || strcasecmp(value, "warning") == 0) {
		return LOG_WARN;
	}
	if (strcasecmp(value, "info") == 0) {
		return LOG_INFO;
	}
	if (strcasecmp(value, "debug") == 0) {
		return LOG_DEBUG;
	}
	if (strcasecmp(value, "trace") == 0) {
		return LOG_TRACE;
	}
	return LOG_INFO;
}

static void ensure_log_init(void) {
	if (g_log_init) {
		return;
	}
	g_log_init = 1;
	const char *level_env = getenv("VXI11_LOG_LEVEL");
	if (level_env && *level_env) {
		g_log_level = parse_log_level(level_env);
	} else {
		const char *debug_env = getenv("VXI11_DEBUG");
		if (debug_env && *debug_env && strcmp(debug_env, "0") != 0) {
			g_log_level = LOG_DEBUG;
		} else {
			g_log_level = LOG_WARN;
		}
	}
	const char *path = getenv("VXI11_LOG_FILE");
	if (path && *path) {
		if (strcasecmp(path, "stderr") == 0) {
			g_log_file = stderr;
		} else if (strcasecmp(path, "stdout") == 0) {
			g_log_file = stdout;
		} else {
			g_log_file = fopen(path, "a");
			if (!g_log_file) {
				g_log_file = stderr;
			}
		}
	} else {
		g_log_file = stderr;
	}
}

static const char *log_basename(const char *path) {
	if (!path || !*path) {
		return "";
	}
	const char *slash = strrchr(path, '/');
	return slash ? slash + 1 : path;
}

static void log_message_v(int level, const char *src, const char *file, int line,
	const char *func, const char *fmt, va_list args) {
	ensure_log_init();
	if (level > g_log_level) {
		return;
	}
	struct timespec ts;
	clock_gettime(CLOCK_REALTIME, &ts);
	time_t sec = ts.tv_sec;
	struct tm tm_now;
	localtime_r(&sec, &tm_now);
	char stamp[32];
	strftime(stamp, sizeof(stamp), "%Y-%m-%d %H:%M:%S", &tm_now);
	int ms = (int)(ts.tv_nsec / 1000000);
	pthread_mutex_lock(&g_log_lock);
	fprintf(g_log_file, "[%s.%03d] %s", stamp, ms, log_level_name(level));
	if (src && *src) {
		fprintf(g_log_file, " %s:", src);
	}
	if (file && *file) {
		fprintf(g_log_file, " %s:%d", log_basename(file), line);
		if (func && *func) {
			fprintf(g_log_file, " %s()", func);
		}
	}
	fprintf(g_log_file, " ");
	vfprintf(g_log_file, fmt, args);
	fprintf(g_log_file, "\n");
	fflush(g_log_file);
	pthread_mutex_unlock(&g_log_lock);
}

static void log_message(int level, const char *src, const char *file, int line,
	const char *func, const char *fmt, ...) {
	va_list args;
	va_start(args, fmt);
	log_message_v(level, src, file, line, func, fmt, args);
	va_end(args);
}

#define LOG_MSG(level, src, fmt, ...) \
	log_message(level, src, __FILE__, __LINE__, __func__, fmt, ##__VA_ARGS__)
#define DEBUG_LOG(fmt, ...) \
	LOG_MSG(LOG_DEBUG, "C", fmt, ##__VA_ARGS__)

static double start_freq_hz_locked(void) {
	return g_center_hz - (g_span_hz / 2.0);
}

static double stop_freq_hz_locked(void) {
	return g_center_hz + (g_span_hz / 2.0);
}

static void update_marker_locked(void) {
	if (g_marker_index < 0) {
		return;
	}
	if (g_marker_index >= g_trace_points) {
		g_marker_index = g_trace_points - 1;
	}
	const double start = start_freq_hz_locked();
	const double step = (g_trace_points > 1) ? (g_span_hz / (g_trace_points - 1)) : 0.0;
	g_marker_freq_hz = start + step * g_marker_index;
	g_marker_level_dbm = g_trace[g_marker_index];
}

static void marker_set_to_max_locked(void) {
	int max_index = 0;
	double max_value = g_trace[0];
	for (int i = 1; i < g_trace_points; ++i) {
		if (g_trace[i] > max_value) {
			max_value = g_trace[i];
			max_index = i;
		}
	}
	g_marker_index = max_index;
	update_marker_locked();
}

static void reseed_noise_locked(void) {
	uint64_t seed = ((uint64_t)time(NULL) << 32) ^ (uint64_t)clock();
	seed ^= (g_noise_counter + 1) * 0x9e3779b97f4a7c15ULL;
	if (seed == 0) {
		seed = 0x243f6a8885a308d3ULL;
	}
	g_noise_counter++;
	g_noise_state = seed;
}

static double next_noise_unit_locked(void) {
	g_noise_state = g_noise_state * 6364136223846793005ULL + 1ULL;
	return (double)((g_noise_state >> 11) & 0x1fffffffffffffULL) / 9007199254740992.0;
}

static void update_tone_drift_locked(void) {
	if (!g_tone_enabled || g_tone_drift_span_hz <= 0.0 || g_tone_drift_step_hz <= 0.0) {
		return;
	}
	const double step = (next_noise_unit_locked() * 2.0 - 1.0) * g_tone_drift_step_hz;
	const double min_freq = g_tone_base_hz - g_tone_drift_span_hz;
	const double max_freq = g_tone_base_hz + g_tone_drift_span_hz;
	g_tone_freq_hz += step;
	if (g_tone_freq_hz < min_freq) {
		g_tone_freq_hz = min_freq;
	} else if (g_tone_freq_hz > max_freq) {
		g_tone_freq_hz = max_freq;
	}
}

static void generate_trace_locked(void) {
	const double start = start_freq_hz_locked();
	const double tone_width = g_span_hz / 400.0;
	const double noise_floor = g_noise_floor_dbm;
	const int points = g_trace_points;
	reseed_noise_locked();
	update_tone_drift_locked();
	for (int i = 0; i < points; ++i) {
		const double frac = (points > 1) ? ((double)i / (points - 1)) : 0.0;
		const double freq = start + g_span_hz * frac;
		const double noise = (next_noise_unit_locked() * 2.0 - 1.0) * g_noise_variation_db;
		const double ripple = 0.5 * sin(i * 0.11) + 0.3 * sin(i * 0.07);
		double level = noise_floor + noise + ripple;
		if (g_tone_enabled) {
			const double offset = freq - g_tone_freq_hz;
			const double amplitude = exp(-(offset * offset) / (2.0 * tone_width * tone_width));
			const double tone = g_tone_level_dbm + 20.0 * log10(amplitude + 1e-12);
			if (tone > level) {
				level = tone;
			}
		}
		g_trace[i] = level;
	}
	if (g_marker_track_max) {
		marker_set_to_max_locked();
	} else {
		update_marker_locked();
	}
}

static void set_error_locked(const char *msg) {
	strncpy(g_error_msg, msg, sizeof(g_error_msg) - 1);
	g_error_msg[sizeof(g_error_msg) - 1] = '\0';
	LOG_MSG(LOG_WARN, "C", "error queued: %s", g_error_msg);
}

static void append_response_locked(const char *response) {
	g_response_len = strlen(response);
	if (g_response_len >= sizeof(g_response)) {
		g_response_len = sizeof(g_response) - 1;
	}
	memcpy(g_response, response, g_response_len);
	g_response[g_response_len] = '\0';
	g_response_offset = 0;
}

static void append_number_response_locked(double value) {
	int written = snprintf(g_response, sizeof(g_response), "%.6e\n", value);
	if (written < 0) {
		append_response_locked("ERROR,\"Format\"\n");
		set_error_locked("-200,\"Execution error\"");
		return;
	}
	g_response_len = (size_t)written;
	g_response_offset = 0;
}

static void append_int_response_locked(int value) {
	int written = snprintf(g_response, sizeof(g_response), "%d\n", value);
	if (written < 0) {
		append_response_locked("ERROR,\"Format\"\n");
		set_error_locked("-200,\"Execution error\"");
		return;
	}
	g_response_len = (size_t)written;
	g_response_offset = 0;
}

static void append_trace_response_locked(void) {
	size_t offset = 0;
	const int points = g_trace_points;
	for (int i = 0; i < points; ++i) {
		const char *fmt = (i + 1 == points) ? "%.6f\n" : "%.6f,";
		int written = snprintf(g_response + offset, sizeof(g_response) - offset, fmt, g_trace[i]);
		if (written < 0) {
			append_response_locked("ERROR,\"Trace\"\n");
			set_error_locked("-200,\"Execution error\"");
			return;
		}
		if ((size_t)written >= sizeof(g_response) - offset) {
			append_response_locked("ERROR,\"Trace\"\n");
			set_error_locked("-200,\"Trace truncated\"");
			return;
		}
		offset += (size_t)written;
	}
	g_response_len = offset;
	g_response_offset = 0;
}

static void trim_whitespace(char *text) {
	char *start = text;
	while (*start && (*start == ' ' || *start == '\t' || *start == '\r' || *start == '\n')) {
		++start;
	}
	char *end = start + strlen(start);
	while (end > start && (end[-1] == ' ' || end[-1] == '\t' || end[-1] == '\r' || end[-1] == '\n')) {
		--end;
	}
	*end = '\0';
	if (start != text) {
		memmove(text, start, (size_t)(end - start) + 1);
	}
}

static void to_upper(char *text) {
	for (; *text; ++text) {
		if (*text >= 'a' && *text <= 'z') {
			*text = (char)(*text - 32);
		}
	}
}

static int parse_double(const char *text, double *out) {
	char *end = NULL;
	double value = strtod(text, &end);
	if (end == text) {
		return 0;
	}
	*out = value;
	return 1;
}

static void maybe_break_on_command_locked(const char *command) {
	const char *break_cmd = getenv("VXI11_BREAK_CMD");
	if (!break_cmd || !*break_cmd) {
		return;
	}
	if (strcmp(break_cmd, "0") == 0 || strcasecmp(break_cmd, "off") == 0) {
		return;
	}
	if (strcasecmp(command, break_cmd) == 0) {
		raise(SIGTRAP);
	}
}

#ifdef VXI11_USE_DUKTAPE
static int read_file(const char *path, char **out, size_t *out_len) {
	FILE *file = fopen(path, "rb");
	if (!file) {
		return 0;
	}
	if (fseek(file, 0, SEEK_END) != 0) {
		fclose(file);
		return 0;
	}
	long size = ftell(file);
	if (size < 0) {
		fclose(file);
		return 0;
	}
	if (fseek(file, 0, SEEK_SET) != 0) {
		fclose(file);
		return 0;
	}
	char *buffer = (char *)malloc((size_t)size + 1);
	if (!buffer) {
		fclose(file);
		return 0;
	}
	size_t read_len = fread(buffer, 1, (size_t)size, file);
	fclose(file);
	buffer[read_len] = '\0';
	*out = buffer;
	*out_len = read_len;
	return 1;
}

static duk_ret_t duk_vxi_get_trace(duk_context *ctx) {
	duk_idx_t arr = duk_push_array(ctx);
	for (duk_uarridx_t i = 0; i < (duk_uarridx_t)g_trace_points; ++i) {
		duk_push_number(ctx, g_trace[i]);
		duk_put_prop_index(ctx, arr, i);
	}
	return 1;
}

static duk_ret_t duk_vxi_set_trace(duk_context *ctx) {
	if (!duk_is_array(ctx, 0)) {
		return duk_error(ctx, DUK_ERR_TYPE_ERROR, "trace must be an array");
	}
	duk_uarridx_t len = duk_get_length(ctx, 0);
	if (len < 1 || len > (duk_uarridx_t)kTraceMaxPoints) {
		return duk_error(ctx, DUK_ERR_RANGE_ERROR, "trace points out of range");
	}
	for (duk_uarridx_t i = 0; i < len; ++i) {
		duk_get_prop_index(ctx, 0, i);
		g_trace[i] = duk_to_number(ctx, -1);
		duk_pop(ctx);
	}
	g_trace_points = (int)len;
	if (g_marker_track_max) {
		marker_set_to_max_locked();
	} else {
		update_marker_locked();
	}
	return 0;
}

static duk_ret_t duk_vxi_get_trace_points(duk_context *ctx) {
	duk_push_int(ctx, g_trace_points);
	return 1;
}

static duk_ret_t duk_vxi_set_trace_points(duk_context *ctx) {
	int points = duk_require_int(ctx, 0);
	if (points < 11 || points > kTraceMaxPoints) {
		return duk_error(ctx, DUK_ERR_RANGE_ERROR, "trace points out of range");
	}
	g_trace_points = points;
	generate_trace_locked();
	return 0;
}

static duk_ret_t duk_vxi_get_center_hz(duk_context *ctx) {
	duk_push_number(ctx, g_center_hz);
	return 1;
}

static duk_ret_t duk_vxi_set_center_hz(duk_context *ctx) {
	g_center_hz = duk_to_number(ctx, 0);
	generate_trace_locked();
	return 0;
}

static duk_ret_t duk_vxi_get_span_hz(duk_context *ctx) {
	duk_push_number(ctx, g_span_hz);
	return 1;
}

static duk_ret_t duk_vxi_set_span_hz(duk_context *ctx) {
	g_span_hz = duk_to_number(ctx, 0);
	generate_trace_locked();
	return 0;
}

static duk_ret_t duk_vxi_get_tone_hz(duk_context *ctx) {
	duk_push_number(ctx, g_tone_freq_hz);
	return 1;
}

static duk_ret_t duk_vxi_set_tone_hz(duk_context *ctx) {
	g_tone_freq_hz = duk_to_number(ctx, 0);
	return 0;
}

static duk_ret_t duk_vxi_set_tone_enabled(duk_context *ctx) {
	g_tone_enabled = duk_to_boolean(ctx, 0) ? 1 : 0;
	return 0;
}

static duk_ret_t duk_vxi_set_noise_floor_dbm(duk_context *ctx) {
	g_noise_floor_dbm = duk_to_number(ctx, 0);
	return 0;
}

static duk_ret_t duk_vxi_set_noise_variation_db(duk_context *ctx) {
	g_noise_variation_db = duk_to_number(ctx, 0);
	return 0;
}

static duk_ret_t duk_vxi_generate_trace(duk_context *ctx) {
	(void)ctx;
	generate_trace_locked();
	return 0;
}

static duk_ret_t duk_vxi_log(duk_context *ctx) {
	int level = LOG_INFO;
	const char *message = NULL;
	if (duk_get_top(ctx) == 1) {
		message = duk_safe_to_string(ctx, 0);
	} else if (duk_get_top(ctx) >= 2) {
		if (duk_is_number(ctx, 0)) {
			level = (int)duk_to_int(ctx, 0);
		} else {
			level = parse_log_level(duk_safe_to_string(ctx, 0));
		}
		message = duk_safe_to_string(ctx, 1);
	}
	if (level < LOG_ERROR) {
		level = LOG_ERROR;
	} else if (level > LOG_TRACE) {
		level = LOG_TRACE;
	}
	if (!message) {
		message = "";
	}
	LOG_MSG(level, "JS", "%s", message);
	return 0;
}

static void register_vxi_api(duk_context *ctx) {
	duk_push_object(ctx);
	duk_push_c_function(ctx, duk_vxi_log, DUK_VARARGS);
	duk_put_prop_string(ctx, -2, "log");
	duk_push_c_function(ctx, duk_vxi_get_trace, 0);
	duk_put_prop_string(ctx, -2, "getTrace");
	duk_push_c_function(ctx, duk_vxi_set_trace, 1);
	duk_put_prop_string(ctx, -2, "setTrace");
	duk_push_c_function(ctx, duk_vxi_get_trace_points, 0);
	duk_put_prop_string(ctx, -2, "getTracePoints");
	duk_push_c_function(ctx, duk_vxi_set_trace_points, 1);
	duk_put_prop_string(ctx, -2, "setTracePoints");
	duk_push_c_function(ctx, duk_vxi_get_center_hz, 0);
	duk_put_prop_string(ctx, -2, "getCenterHz");
	duk_push_c_function(ctx, duk_vxi_set_center_hz, 1);
	duk_put_prop_string(ctx, -2, "setCenterHz");
	duk_push_c_function(ctx, duk_vxi_get_span_hz, 0);
	duk_put_prop_string(ctx, -2, "getSpanHz");
	duk_push_c_function(ctx, duk_vxi_set_span_hz, 1);
	duk_put_prop_string(ctx, -2, "setSpanHz");
	duk_push_c_function(ctx, duk_vxi_get_tone_hz, 0);
	duk_put_prop_string(ctx, -2, "getToneHz");
	duk_push_c_function(ctx, duk_vxi_set_tone_hz, 1);
	duk_put_prop_string(ctx, -2, "setToneHz");
	duk_push_c_function(ctx, duk_vxi_set_tone_enabled, 1);
	duk_put_prop_string(ctx, -2, "setToneEnabled");
	duk_push_c_function(ctx, duk_vxi_set_noise_floor_dbm, 1);
	duk_put_prop_string(ctx, -2, "setNoiseFloorDbm");
	duk_push_c_function(ctx, duk_vxi_set_noise_variation_db, 1);
	duk_put_prop_string(ctx, -2, "setNoiseVariationDb");
	duk_push_c_function(ctx, duk_vxi_generate_trace, 0);
	duk_put_prop_string(ctx, -2, "generateTrace");
	duk_put_global_string(ctx, "vxi");
}

static int script_init_locked(void) {
	if (g_script_init) {
		return g_script_enabled;
	}
	g_script_init = 1;
	const char *env = getenv("VXI11_SCRIPT");
	if (env && (*env == '\0' || strcmp(env, "0") == 0 || strcasecmp(env, "off") == 0)) {
		return 0;
	}
	const char *path = env && *env ? env : "scpi/vxi11_script.js";
	char *script = NULL;
	size_t script_len = 0;
	if (!read_file(path, &script, &script_len)) {
		if (env && *env) {
			LOG_MSG(LOG_WARN, "JS", "script not found: %s", path);
		}
		return 0;
	}
	g_duk_ctx = duk_create_heap_default();
	if (!g_duk_ctx) {
		LOG_MSG(LOG_ERROR, "JS", "failed to create duktape heap");
		free(script);
		return 0;
	}
	register_vxi_api(g_duk_ctx);
	if (duk_peval_lstring(g_duk_ctx, script, script_len) != 0) {
		LOG_MSG(LOG_ERROR, "JS", "script error: %s", duk_safe_to_string(g_duk_ctx, -1));
		duk_pop(g_duk_ctx);
		duk_destroy_heap(g_duk_ctx);
		g_duk_ctx = NULL;
		free(script);
		return 0;
	}
	duk_pop(g_duk_ctx);
	free(script);
	strncpy(g_script_path, path, sizeof(g_script_path) - 1);
	g_script_path[sizeof(g_script_path) - 1] = '\0';
	g_script_enabled = 1;
	LOG_MSG(LOG_INFO, "JS", "script loaded: %s", g_script_path);
	return 1;
}
#endif

static int script_handle_command_locked(const char *command, char *out, size_t out_size, size_t *out_len) {
#ifdef VXI11_USE_DUKTAPE
	if (!out || out_size == 0) {
		return 0;
	}
	if (!script_init_locked()) {
		return 0;
	}
	duk_context *ctx = g_duk_ctx;
	duk_get_global_string(ctx, "handle");
	if (!duk_is_function(ctx, -1)) {
		duk_pop(ctx);
		LOG_MSG(LOG_WARN, "JS", "handle() not defined");
		return 0;
	}
	LOG_MSG(LOG_TRACE, "JS", "handle cmd=\"%s\"", command);
	duk_push_string(ctx, command);
	if (duk_pcall(ctx, 1) != 0) {
		LOG_MSG(LOG_ERROR, "JS", "handle error: %s", duk_safe_to_string(ctx, -1));
		duk_pop(ctx);
		return 0;
	}
	if (duk_is_null(ctx, -1) || duk_is_undefined(ctx, -1)) {
		duk_pop(ctx);
		LOG_MSG(LOG_DEBUG, "JS", "no handler for cmd=\"%s\"", command);
		return 0;
	}
	const char *resp = duk_safe_to_string(ctx, -1);
	size_t len = strlen(resp);
	if (len >= out_size) {
		len = out_size - 1;
	}
	memcpy(out, resp, len);
	if (len + 1 < out_size && len > 0 && out[len - 1] != '\n') {
		out[len++] = '\n';
	}
	out[len] = '\0';
	if (out_len) {
		*out_len = len;
	}
	duk_pop(ctx);
	LOG_MSG(LOG_DEBUG, "JS", "handled cmd=\"%s\" len=%zu", command, len);
	return 1;
#else
	(void)command;
	(void)out;
	(void)out_size;
	(void)out_len;
	return 0;
#endif
}

static void prepare_response_locked(const char *command) {
	char buffer[1024];
	strncpy(buffer, command, sizeof(buffer) - 1);
	buffer[sizeof(buffer) - 1] = '\0';
	trim_whitespace(buffer);
	if (buffer[0] == '\0') {
		append_response_locked("");
		return;
	}

	size_t script_len = 0;
	if (script_handle_command_locked(buffer, g_response, sizeof(g_response), &script_len)) {
		g_response_len = script_len < sizeof(g_response) ? script_len : sizeof(g_response) - 1;
		g_response[g_response_len] = '\0';
		g_response_offset = 0;
		return;
	}

	char *arg = NULL;
	for (char *p = buffer; *p; ++p) {
		if (*p == ' ' || *p == '\t') {
			*p = '\0';
			arg = p + 1;
			break;
		}
	}
	if (arg) {
		trim_whitespace(arg);
	}

	to_upper(buffer);
	maybe_break_on_command_locked(buffer);
	LOG_MSG(LOG_DEBUG, "C", "cmd=\"%s\" arg=\"%s\"", buffer, arg ? arg : "");

	if (strcmp(buffer, "*IDN?") == 0) {
		append_response_locked("AGILENT,PSA-N9030A,SGNL0001,5.00\n");
		return;
	}
	if (strcmp(buffer, "*RST") == 0) {
		reset_state_locked();
		generate_trace_locked();
		append_response_locked("OK\n");
		return;
	}
	if (strcmp(buffer, ":SYST:ERR?") == 0 || strcmp(buffer, ":SYSTEM:ERROR?") == 0) {
		if (g_error_msg[0] == '\0') {
			append_response_locked("0,\"No error\"\n");
		} else {
			append_response_locked(g_error_msg);
			if (g_response_len + 1 < sizeof(g_response)) {
				g_response[g_response_len++] = '\n';
				g_response[g_response_len] = '\0';
			}
			g_error_msg[0] = '\0';
			g_response_offset = 0;
		}
		return;
	}

	if (strcmp(buffer, ":SENS:FREQ:CENT?") == 0 || strcmp(buffer, ":SENSE:FREQUENCY:CENTER?") == 0) {
		append_number_response_locked(g_center_hz);
		return;
	}
	if (strcmp(buffer, ":FREQ:STAR?") == 0 || strcmp(buffer, ":FREQUENCY:START?") == 0) {
		append_number_response_locked(start_freq_hz_locked());
		return;
	}
	if (strcmp(buffer, ":FREQ:STOP?") == 0 || strcmp(buffer, ":FREQUENCY:STOP?") == 0) {
		append_number_response_locked(stop_freq_hz_locked());
		return;
	}
	if (strcmp(buffer, ":SENS:FREQ:SPAN?") == 0 || strcmp(buffer, ":SENSE:FREQUENCY:SPAN?") == 0) {
		append_number_response_locked(g_span_hz);
		return;
	}
	if (strcmp(buffer, ":SENS:BAND:RES?") == 0 || strcmp(buffer, ":SENSE:BANDWIDTH:RESOLUTION?") == 0) {
		append_number_response_locked(g_rbw_hz);
		return;
	}
	if (strcmp(buffer, ":BAND:VID?") == 0 || strcmp(buffer, ":BANDWIDTH:VIDEO?") == 0) {
		append_number_response_locked(g_vbw_hz);
		return;
	}
	if (strcmp(buffer, ":SWE:POIN?") == 0 || strcmp(buffer, ":SWEEP:POINTS?") == 0) {
		append_int_response_locked(g_trace_points);
		return;
	}
	if (strcmp(buffer, ":SWE:TIME?") == 0 || strcmp(buffer, ":SWEEP:TIME?") == 0) {
		append_number_response_locked(g_sweep_time_s);
		return;
	}
	if (strcmp(buffer, ":DISP:WIND:TRAC:Y:SCAL:RLEV?") == 0 ||
	    strcmp(buffer, ":DISPLAY:WINDOW:TRACE:Y:SCALE:RLEVEL?") == 0) {
		append_number_response_locked(g_ref_level_dbm);
		return;
	}
	if (strcmp(buffer, ":INIT:CONT?") == 0 || strcmp(buffer, ":INITIATE:CONTINUOUS?") == 0) {
		append_int_response_locked(g_continuous ? 1 : 0);
		return;
	}
	if (strcmp(buffer, ":CALC:MARK1:X?") == 0 || strcmp(buffer, ":CALCULATE:MARKER1:X?") == 0) {
		if (g_marker_index < 0) {
			marker_set_to_max_locked();
		}
		append_number_response_locked(g_marker_freq_hz);
		return;
	}
	if (strcmp(buffer, ":CALC:MARK1:Y?") == 0 || strcmp(buffer, ":CALCULATE:MARKER1:Y?") == 0) {
		if (g_marker_index < 0) {
			marker_set_to_max_locked();
		}
		append_number_response_locked(g_marker_level_dbm);
		return;
	}

	if (strcmp(buffer, ":SENS:FREQ:CENT") == 0 || strcmp(buffer, ":SENSE:FREQUENCY:CENTER") == 0) {
		double value;
		if (!arg || !parse_double(arg, &value)) {
			append_response_locked("ERROR,\"Bad value\"\n");
			set_error_locked("-222,\"Data out of range\"");
			return;
		}
		g_center_hz = value;
		append_response_locked("OK\n");
		return;
	}
	if (strcmp(buffer, ":FREQ:STAR") == 0 || strcmp(buffer, ":FREQUENCY:START") == 0) {
		double value;
		if (!arg || !parse_double(arg, &value)) {
			append_response_locked("ERROR,\"Bad value\"\n");
			set_error_locked("-222,\"Data out of range\"");
			return;
		}
		const double stop = stop_freq_hz_locked();
		if (value >= stop) {
			append_response_locked("ERROR,\"Bad value\"\n");
			set_error_locked("-222,\"Data out of range\"");
			return;
		}
		g_center_hz = (value + stop) / 2.0;
		g_span_hz = stop - value;
		generate_trace_locked();
		append_response_locked("OK\n");
		return;
	}
	if (strcmp(buffer, ":FREQ:STOP") == 0 || strcmp(buffer, ":FREQUENCY:STOP") == 0) {
		double value;
		if (!arg || !parse_double(arg, &value)) {
			append_response_locked("ERROR,\"Bad value\"\n");
			set_error_locked("-222,\"Data out of range\"");
			return;
		}
		const double start = start_freq_hz_locked();
		if (value <= start) {
			append_response_locked("ERROR,\"Bad value\"\n");
			set_error_locked("-222,\"Data out of range\"");
			return;
		}
		g_center_hz = (start + value) / 2.0;
		g_span_hz = value - start;
		generate_trace_locked();
		append_response_locked("OK\n");
		return;
	}
	if (strcmp(buffer, ":SENS:FREQ:SPAN") == 0 || strcmp(buffer, ":SENSE:FREQUENCY:SPAN") == 0) {
		double value;
		if (!arg || !parse_double(arg, &value)) {
			append_response_locked("ERROR,\"Bad value\"\n");
			set_error_locked("-222,\"Data out of range\"");
			return;
		}
		g_span_hz = value;
		generate_trace_locked();
		append_response_locked("OK\n");
		return;
	}
	if (strcmp(buffer, ":SENS:BAND:RES") == 0 || strcmp(buffer, ":SENSE:BANDWIDTH:RESOLUTION") == 0) {
		double value;
		if (!arg || !parse_double(arg, &value)) {
			append_response_locked("ERROR,\"Bad value\"\n");
			set_error_locked("-222,\"Data out of range\"");
			return;
		}
		g_rbw_hz = value;
		append_response_locked("OK\n");
		return;
	}
	if (strcmp(buffer, ":BAND:VID") == 0 || strcmp(buffer, ":BANDWIDTH:VIDEO") == 0) {
		double value;
		if (!arg || !parse_double(arg, &value)) {
			append_response_locked("ERROR,\"Bad value\"\n");
			set_error_locked("-222,\"Data out of range\"");
			return;
		}
		g_vbw_hz = value;
		append_response_locked("OK\n");
		return;
	}
	if (strcmp(buffer, ":SWE:POIN") == 0 || strcmp(buffer, ":SWEEP:POINTS") == 0) {
		double value;
		if (!arg || !parse_double(arg, &value)) {
			append_response_locked("ERROR,\"Bad value\"\n");
			set_error_locked("-222,\"Data out of range\"");
			return;
		}
		int points = (int)value;
		if (points < 11 || points > kTraceMaxPoints) {
			append_response_locked("ERROR,\"Bad points\"\n");
			set_error_locked("-222,\"Data out of range\"");
			return;
		}
		g_trace_points = points;
		generate_trace_locked();
		append_response_locked("OK\n");
		return;
	}
	if (strcmp(buffer, ":SWE:TIME") == 0 || strcmp(buffer, ":SWEEP:TIME") == 0) {
		double value;
		if (!arg || !parse_double(arg, &value)) {
			append_response_locked("ERROR,\"Bad value\"\n");
			set_error_locked("-222,\"Data out of range\"");
			return;
		}
		g_sweep_time_s = value;
		append_response_locked("OK\n");
		return;
	}
	if (strcmp(buffer, ":DISP:WIND:TRAC:Y:SCAL:RLEV") == 0 ||
	    strcmp(buffer, ":DISPLAY:WINDOW:TRACE:Y:SCALE:RLEVEL") == 0) {
		double value;
		if (!arg || !parse_double(arg, &value)) {
			append_response_locked("ERROR,\"Bad value\"\n");
			set_error_locked("-222,\"Data out of range\"");
			return;
		}
		g_ref_level_dbm = value;
		generate_trace_locked();
		append_response_locked("OK\n");
		return;
	}

	if (strcmp(buffer, ":INIT") == 0 || strcmp(buffer, ":INITIATE") == 0 ||
	    strcmp(buffer, ":INIT:IMM") == 0 || strcmp(buffer, ":INITIATE:IMMEDIATE") == 0) {
		generate_trace_locked();
		append_response_locked("OK\n");
		return;
	}
	if (strcmp(buffer, ":INIT:CONT") == 0 || strcmp(buffer, ":INITIATE:CONTINUOUS") == 0) {
		double value;
		if (!arg || !parse_double(arg, &value)) {
			append_response_locked("ERROR,\"Bad value\"\n");
			set_error_locked("-222,\"Data out of range\"");
			return;
		}
		g_continuous = value != 0.0 ? 1 : 0;
		append_response_locked("OK\n");
		return;
	}
	if (strcmp(buffer, ":CALC:MARK1:MAX") == 0 || strcmp(buffer, ":CALCULATE:MARKER1:MAXIMUM") == 0) {
		g_marker_track_max = 1;
		marker_set_to_max_locked();
		append_response_locked("OK\n");
		return;
	}
	if (strcmp(buffer, ":TRAC:DATA?") == 0 || strcmp(buffer, ":TRACE:DATA?") == 0) {
		append_trace_response_locked();
		return;
	 }

	LOG_MSG(LOG_WARN, "C", "unknown cmd=\"%s\"", buffer);
	append_response_locked("ERROR,\"Unknown command\"\n");
	set_error_locked("-113,\"Undefined header\"");
}

Device_Error *
device_abort_1_svc(Device_Link *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Create_LinkResp *
create_link_1_svc(Create_LinkParms *argp, struct svc_req *rqstp)
{
	static Create_LinkResp  result;
	(void)argp;
	(void)rqstp;
	ensure_log_init();
	pthread_mutex_lock(&g_state_lock);
	g_last_command[0] = '\0';
	g_response[0] = '\0';
	g_response_len = 0;
	g_response_offset = 0;
	reset_state_locked();
	generate_trace_locked();
#ifdef VXI11_USE_DUKTAPE
	script_init_locked();
#endif
	pthread_mutex_unlock(&g_state_lock);
	result.error = 0;
	result.lid = kLinkId;
	result.abortPort = 0;
	result.maxRecvSize = (u_int)sizeof(g_response);
	LOG_MSG(LOG_INFO, "RPC", "create_link lid=%d maxRecv=%u", result.lid, result.maxRecvSize);
	DEBUG_LOG("[vxi11] create_link lid=%d maxRecv=%u", result.lid, result.maxRecvSize);
	return &result;
}

Device_WriteResp *
device_write_1_svc(Device_WriteParms *argp, struct svc_req *rqstp)
{
	static Device_WriteResp  result;
	(void)rqstp;
	ensure_log_init();
	pthread_mutex_lock(&g_state_lock);
	size_t copy_len = argp->data.data_len;
	if (copy_len >= sizeof(g_last_command)) {
		copy_len = sizeof(g_last_command) - 1;
	}
	memcpy(g_last_command, argp->data.data_val, copy_len);
	g_last_command[copy_len] = '\0';
	DEBUG_LOG("[vxi11] write cmd=\"%s\"", g_last_command);
	prepare_response_locked(g_last_command);
	pthread_mutex_unlock(&g_state_lock);
	result.error = 0;
	result.size = (u_int)copy_len;
	return &result;
}

Device_ReadResp *
device_read_1_svc(Device_ReadParms *argp, struct svc_req *rqstp)
{
	static Device_ReadResp  result;
	static char buffer[4096];
	(void)argp;
	(void)rqstp;
	ensure_log_init();
	pthread_mutex_lock(&g_state_lock);
	size_t remaining = 0;
	if (g_response_len > g_response_offset) {
		remaining = g_response_len - g_response_offset;
	}
	size_t max_len = argp->requestSize;
	if (max_len > sizeof(buffer)) {
		max_len = sizeof(buffer);
	}
	size_t send_len = remaining < max_len ? remaining : max_len;
	if (send_len > 0) {
		memcpy(buffer, g_response + g_response_offset, send_len);
	}
	g_response_offset += send_len;
	const int reason = (g_response_offset >= g_response_len) ? 1 : 0;
	pthread_mutex_unlock(&g_state_lock);
	result.error = 0;
	result.reason = reason;
	result.data.data_val = buffer;
	result.data.data_len = (u_int)send_len;
	DEBUG_LOG("[vxi11] read send=%zu offset=%zu len=%zu reason=%d",
		send_len, g_response_offset, g_response_len, reason);
	return &result;
}

Device_ReadStbResp *
device_readstb_1_svc(Device_GenericParms *argp, struct svc_req *rqstp)
{
	static Device_ReadStbResp  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Device_Error *
device_trigger_1_svc(Device_GenericParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Device_Error *
device_clear_1_svc(Device_GenericParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Device_Error *
device_remote_1_svc(Device_GenericParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Device_Error *
device_local_1_svc(Device_GenericParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Device_Error *
device_lock_1_svc(Device_LockParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Device_Error *
device_unlock_1_svc(Device_Link *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Device_Error *
device_enable_srq_1_svc(Device_EnableSrqParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Device_DocmdResp *
device_docmd_1_svc(Device_DocmdParms *argp, struct svc_req *rqstp)
{
	static Device_DocmdResp  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Device_Error *
destroy_link_1_svc(Device_Link *argp, struct svc_req *rqstp)
{
	static Device_Error  result;
	(void)argp;
	(void)rqstp;
	result.error = 0;
	return &result;
}

Device_Error *
create_intr_chan_1_svc(Device_RemoteFunc *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Device_Error *
destroy_intr_chan_1_svc(void *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */

	return &result;
}
