/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "vxi11core.h"
#include <math.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>

static pthread_mutex_t g_state_lock = PTHREAD_MUTEX_INITIALIZER;
static char g_last_command[1024];
static char g_response[65536];
static size_t g_response_len = 0;
static size_t g_response_offset = 0;
static const Device_Link kLinkId = 1;

static const int kTracePoints = 1001;
static double g_trace[1001];
static double g_center_hz = 1.0e9;
static double g_span_hz = 10.0e6;
static double g_ref_level_dbm = 0.0;
static double g_rbw_hz = 1.0e3;
static char g_error_msg[128];

static void reset_state_locked(void) {
	g_center_hz = 1.0e9;
	g_span_hz = 10.0e6;
	g_ref_level_dbm = 0.0;
	g_rbw_hz = 1.0e3;
	g_error_msg[0] = '\0';
}

static void generate_trace_locked(void) {
	const double peak_freq = g_center_hz + g_span_hz * 0.1;
	const double width = g_span_hz / 6.0;
	for (int i = 0; i < kTracePoints; ++i) {
		const double frac = (kTracePoints > 1) ? ((double)i / (kTracePoints - 1)) : 0.0;
		const double freq = g_center_hz - g_span_hz / 2.0 + g_span_hz * frac;
		const double offset = freq - peak_freq;
		const double gaussian = g_ref_level_dbm - 10.0 * exp(-(offset * offset) / (2.0 * width * width));
		g_trace[i] = gaussian;
	}
}

static void set_error_locked(const char *msg) {
	strncpy(g_error_msg, msg, sizeof(g_error_msg) - 1);
	g_error_msg[sizeof(g_error_msg) - 1] = '\0';
}

static void append_response_locked(const char *response) {
	g_response_len = strlen(response);
	if (g_response_len >= sizeof(g_response)) {
		g_response_len = sizeof(g_response) - 1;
	}
	memcpy(g_response, response, g_response_len);
	g_response[g_response_len] = '\0';
	g_response_offset = 0;
}

static void append_number_response_locked(double value) {
	int written = snprintf(g_response, sizeof(g_response), "%.6e\n", value);
	if (written < 0) {
		append_response_locked("ERROR,\"Format\"\n");
		set_error_locked("-200,\"Execution error\"");
		return;
	}
	g_response_len = (size_t)written;
	g_response_offset = 0;
}

static void append_trace_response_locked(void) {
	size_t offset = 0;
	for (int i = 0; i < kTracePoints; ++i) {
		const char *fmt = (i + 1 == kTracePoints) ? "%.6f\n" : "%.6f,";
		int written = snprintf(g_response + offset, sizeof(g_response) - offset, fmt, g_trace[i]);
		if (written < 0) {
			append_response_locked("ERROR,\"Trace\"\n");
			set_error_locked("-200,\"Execution error\"");
			return;
		}
		if ((size_t)written >= sizeof(g_response) - offset) {
			append_response_locked("ERROR,\"Trace\"\n");
			set_error_locked("-200,\"Trace truncated\"");
			return;
		}
		offset += (size_t)written;
	}
	g_response_len = offset;
	g_response_offset = 0;
}

static void trim_whitespace(char *text) {
	char *start = text;
	while (*start && (*start == ' ' || *start == '\t' || *start == '\r' || *start == '\n')) {
		++start;
	}
	char *end = start + strlen(start);
	while (end > start && (end[-1] == ' ' || end[-1] == '\t' || end[-1] == '\r' || end[-1] == '\n')) {
		--end;
	}
	*end = '\0';
	if (start != text) {
		memmove(text, start, (size_t)(end - start) + 1);
	}
}

static void to_upper(char *text) {
	for (; *text; ++text) {
		if (*text >= 'a' && *text <= 'z') {
			*text = (char)(*text - 32);
		}
	}
}

static int parse_double(const char *text, double *out) {
	char *end = NULL;
	double value = strtod(text, &end);
	if (end == text) {
		return 0;
	}
	*out = value;
	return 1;
}

static void prepare_response_locked(const char *command) {
	char buffer[1024];
	strncpy(buffer, command, sizeof(buffer) - 1);
	buffer[sizeof(buffer) - 1] = '\0';
	trim_whitespace(buffer);
	if (buffer[0] == '\0') {
		append_response_locked("");
		return;
	}

	char *arg = NULL;
	for (char *p = buffer; *p; ++p) {
		if (*p == ' ' || *p == '\t') {
			*p = '\0';
			arg = p + 1;
			break;
		}
	}
	if (arg) {
		trim_whitespace(arg);
	}

	to_upper(buffer);

	if (strcmp(buffer, "*IDN?") == 0) {
		append_response_locked("AGILENT,PSA-N9030A,SGNL0001,5.00\n");
		return;
	}
	if (strcmp(buffer, "*RST") == 0) {
		reset_state_locked();
		generate_trace_locked();
		append_response_locked("OK\n");
		return;
	}
	if (strcmp(buffer, ":SYST:ERR?") == 0 || strcmp(buffer, ":SYSTEM:ERROR?") == 0) {
		if (g_error_msg[0] == '\0') {
			append_response_locked("0,\"No error\"\n");
		} else {
			append_response_locked(g_error_msg);
			if (g_response_len + 1 < sizeof(g_response)) {
				g_response[g_response_len++] = '\n';
				g_response[g_response_len] = '\0';
			}
			g_error_msg[0] = '\0';
			g_response_offset = 0;
		}
		return;
	}

	if (strcmp(buffer, ":SENS:FREQ:CENT?") == 0 || strcmp(buffer, ":SENSE:FREQUENCY:CENTER?") == 0) {
		append_number_response_locked(g_center_hz);
		return;
	}
	if (strcmp(buffer, ":SENS:FREQ:SPAN?") == 0 || strcmp(buffer, ":SENSE:FREQUENCY:SPAN?") == 0) {
		append_number_response_locked(g_span_hz);
		return;
	}
	if (strcmp(buffer, ":SENS:BAND:RES?") == 0 || strcmp(buffer, ":SENSE:BANDWIDTH:RESOLUTION?") == 0) {
		append_number_response_locked(g_rbw_hz);
		return;
	}
	if (strcmp(buffer, ":DISP:WIND:TRAC:Y:SCAL:RLEV?") == 0 ||
	    strcmp(buffer, ":DISPLAY:WINDOW:TRACE:Y:SCALE:RLEVEL?") == 0) {
		append_number_response_locked(g_ref_level_dbm);
		return;
	}

	if (strcmp(buffer, ":SENS:FREQ:CENT") == 0 || strcmp(buffer, ":SENSE:FREQUENCY:CENTER") == 0) {
		double value;
		if (!arg || !parse_double(arg, &value)) {
			append_response_locked("ERROR,\"Bad value\"\n");
			set_error_locked("-222,\"Data out of range\"");
			return;
		}
		g_center_hz = value;
		append_response_locked("OK\n");
		return;
	}
	if (strcmp(buffer, ":SENS:FREQ:SPAN") == 0 || strcmp(buffer, ":SENSE:FREQUENCY:SPAN") == 0) {
		double value;
		if (!arg || !parse_double(arg, &value)) {
			append_response_locked("ERROR,\"Bad value\"\n");
			set_error_locked("-222,\"Data out of range\"");
			return;
		}
		g_span_hz = value;
		generate_trace_locked();
		append_response_locked("OK\n");
		return;
	}
	if (strcmp(buffer, ":SENS:BAND:RES") == 0 || strcmp(buffer, ":SENSE:BANDWIDTH:RESOLUTION") == 0) {
		double value;
		if (!arg || !parse_double(arg, &value)) {
			append_response_locked("ERROR,\"Bad value\"\n");
			set_error_locked("-222,\"Data out of range\"");
			return;
		}
		g_rbw_hz = value;
		append_response_locked("OK\n");
		return;
	}
	if (strcmp(buffer, ":DISP:WIND:TRAC:Y:SCAL:RLEV") == 0 ||
	    strcmp(buffer, ":DISPLAY:WINDOW:TRACE:Y:SCALE:RLEVEL") == 0) {
		double value;
		if (!arg || !parse_double(arg, &value)) {
			append_response_locked("ERROR,\"Bad value\"\n");
			set_error_locked("-222,\"Data out of range\"");
			return;
		}
		g_ref_level_dbm = value;
		generate_trace_locked();
		append_response_locked("OK\n");
		return;
	}

	if (strcmp(buffer, ":INIT") == 0 || strcmp(buffer, ":INITIATE") == 0) {
		generate_trace_locked();
		append_response_locked("OK\n");
		return;
	}
	if (strcmp(buffer, ":TRAC:DATA?") == 0 || strcmp(buffer, ":TRACE:DATA?") == 0) {
		append_trace_response_locked();
		return;
	}

	append_response_locked("ERROR,\"Unknown command\"\n");
	set_error_locked("-113,\"Undefined header\"");
}

Device_Error *
device_abort_1_svc(Device_Link *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Create_LinkResp *
create_link_1_svc(Create_LinkParms *argp, struct svc_req *rqstp)
{
	static Create_LinkResp  result;
	(void)argp;
	(void)rqstp;
	pthread_mutex_lock(&g_state_lock);
	g_last_command[0] = '\0';
	g_response[0] = '\0';
	g_response_len = 0;
	g_response_offset = 0;
	reset_state_locked();
	generate_trace_locked();
	pthread_mutex_unlock(&g_state_lock);
	result.error = 0;
	result.lid = kLinkId;
	result.abortPort = 0;
	result.maxRecvSize = (u_int)sizeof(g_response);
	return &result;
}

Device_WriteResp *
device_write_1_svc(Device_WriteParms *argp, struct svc_req *rqstp)
{
	static Device_WriteResp  result;
	(void)rqstp;
	pthread_mutex_lock(&g_state_lock);
	size_t copy_len = argp->data.data_len;
	if (copy_len >= sizeof(g_last_command)) {
		copy_len = sizeof(g_last_command) - 1;
	}
	memcpy(g_last_command, argp->data.data_val, copy_len);
	g_last_command[copy_len] = '\0';
	prepare_response_locked(g_last_command);
	pthread_mutex_unlock(&g_state_lock);
	result.error = 0;
	result.size = (u_int)copy_len;
	return &result;
}

Device_ReadResp *
device_read_1_svc(Device_ReadParms *argp, struct svc_req *rqstp)
{
	static Device_ReadResp  result;
	static char buffer[4096];
	(void)argp;
	(void)rqstp;
	pthread_mutex_lock(&g_state_lock);
	size_t remaining = 0;
	if (g_response_len > g_response_offset) {
		remaining = g_response_len - g_response_offset;
	}
	size_t max_len = argp->requestSize;
	if (max_len > sizeof(buffer)) {
		max_len = sizeof(buffer);
	}
	size_t send_len = remaining < max_len ? remaining : max_len;
	if (send_len > 0) {
		memcpy(buffer, g_response + g_response_offset, send_len);
	}
	g_response_offset += send_len;
	pthread_mutex_unlock(&g_state_lock);
	result.error = 0;
	result.reason = (g_response_offset >= g_response_len) ? 1 : 0;
	result.data.data_val = buffer;
	result.data.data_len = (u_int)send_len;
	return &result;
}

Device_ReadStbResp *
device_readstb_1_svc(Device_GenericParms *argp, struct svc_req *rqstp)
{
	static Device_ReadStbResp  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Device_Error *
device_trigger_1_svc(Device_GenericParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Device_Error *
device_clear_1_svc(Device_GenericParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Device_Error *
device_remote_1_svc(Device_GenericParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Device_Error *
device_local_1_svc(Device_GenericParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Device_Error *
device_lock_1_svc(Device_LockParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Device_Error *
device_unlock_1_svc(Device_Link *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Device_Error *
device_enable_srq_1_svc(Device_EnableSrqParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Device_DocmdResp *
device_docmd_1_svc(Device_DocmdParms *argp, struct svc_req *rqstp)
{
	static Device_DocmdResp  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Device_Error *
destroy_link_1_svc(Device_Link *argp, struct svc_req *rqstp)
{
	static Device_Error  result;
	(void)argp;
	(void)rqstp;
	result.error = 0;
	return &result;
}

Device_Error *
create_intr_chan_1_svc(Device_RemoteFunc *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */

	return &result;
}

Device_Error *
destroy_intr_chan_1_svc(void *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */

	return &result;
}
